### ISSUE TITLE
NoClassDefFoundError on EmbeddedKafkaCluster initialisation

### ISSUE THREAD

**Issue by DanielAmorim** [mguenther/kafka-junit#45]
The provision of `EmbeddedKafkaCluster`, with the default configurations, is throwing a `NoClassDefFoundError`.

Code:
> EmbeddedKafkaCluster.provisionWith(EmbeddedKafkaClusterConfig.useDefaults())

Error:
```
org/apache/kafka/common/config/SslClientAuth
java.lang.NoClassDefFoundError: org/apache/kafka/common/config/SslClientAuth
    at kafka.server.Defaults$.<init>(KafkaConfig.scala:222)
    at kafka.server.Defaults$.<clinit>(KafkaConfig.scala)
    at kafka.server.KafkaConfig$.<init>(KafkaConfig.scala:854)
    at kafka.server.KafkaConfig$.<clinit>(KafkaConfig.scala)
    at net.mguenther.kafka.junit.EmbeddedKafkaConfig$EmbeddedKafkaConfigBuilder.build(EmbeddedKafkaConfig.java:44)
    at net.mguenther.kafka.junit.EmbeddedKafkaConfig.useDefaults(EmbeddedKafkaConfig.java:77)
    at net.mguenther.kafka.junit.EmbeddedKafkaClusterConfig$EmbeddedKafkaClusterConfigBuilder.<init>(EmbeddedKafkaClusterConfig.java:16)
    at net.mguenther.kafka.junit.EmbeddedKafkaClusterConfig.create(EmbeddedKafkaClusterConfig.java:51)
    at net.mguenther.kafka.junit.EmbeddedKafkaClusterConfig.useDefaults(EmbeddedKafkaClusterConfig.java:55)
    at com.github.danielamorim.ApplicationTest.should embeddedKafkaCluster different of null(ApplicationTest.kt:18)
```
This error only occurs when `kafka-clients` library is a dependency of the project.

I created a repository (see [here](https://github.com/DanielAmorim/junit-for-kakfa-with-srping-boot)) to anyone can replicate the issue. The `master` branch are working well and the `feature/add_kafka_clients_library` aren't working, because the it has the `kafka-clients` library as dependency of the project.

Note: I only faced this issue after update the `srping boot` version from `2.1.X` to `2.2.X`

Note 2: I already tried to update the `kafka` and `kafka-junit` libraries to the latest version, but the issue persists.

**Comment by mguenther** [comment]
This is actually not an issue with kafka-junit, but a dependency management issue in your setup. When looking at the output of `gradle dependencies` you'll notice that Gradle selects `org.apache.kafka:kafka-clients:2.3.1` (introduced by the dependency management of Spring Boot 2.2.6.RELEASE) over `org.apache.kafka:kafka-clients:2.0.0` (which is used in `kafka-junit:2.0.0`).

Spring Boot 2.1.x manages `org.springframework.kafka:spring-kafka:2.2.5.RELEASE` which introduces `org.apache.kafka:kafka-clients:2.0.1` (compatible with `kafka-junit:2.0.0` since the `kafka-clients` only diverge in their patch version).

Spring Boot 2.2.6.RELEASE on the other hand manages `org.springframework.kafka:spring-kafka:2.3.7.RELEASE` which introduces `org.apache.kafka:kafka-clients:2.3.1` (not compatible with `kafka-junit:2.0.0`).

I can't say why your override (`kafkaVersion = '2.0.0'`) does not work properly, as I'm not a Gradle user. But intentionally overriding the BOM property to the versions that are compatible with `kafka-junit:2.0.0` should do the job.

Add this to your `build.gradle`:

```gradle
dependencyManagement {
    imports {
        mavenBom('org.springframework.boot:spring-boot-dependencies:2.2.6.RELEASE') {
            bomProperty 'spring-kafka.version', '2.2.5.RELEASE'
            bomProperty 'kafka.version', '2.0.0'
        }
    }
}
```

No guarantees though if overriding these properties won't introduce other problems. You'll have to carefully check if this approach is suitable for your project setup.
