### ISSUE TITLE
question: is it possible to define random ports for the cluster

### ISSUE THREAD

**Issue by cstmgl** [mguenther/kafka-junit#91]
hi...
I'm looking at the code and I can't really find it, neither on my side, nor in here but is it possible to define random ports for the kafka-cluster?

I never had issues but I'm not using this cluster in a multi project setup in gradle and I'm having tests failures because the cluster cannot start with port already bound.

```
Caused by: java.lang.RuntimeException: Unable to start the embedded Kafka broker with ID 1.
	at net.mguenther.kafka.junit.EmbeddedKafka.activate(EmbeddedKafka.java:77)
	at net.mguenther.kafka.junit.EmbeddedKafka.start(EmbeddedKafka.java:54)
	at net.mguenther.kafka.junit.EmbeddedKafkaCluster.start(EmbeddedKafkaCluster.java:52)
	... 75 more
Caused by: org.apache.kafka.common.KafkaException: Socket server failed to bind to localhost:9092: Address already in use.
	at app//kafka.network.Acceptor.openServerSocket(SocketServer.scala:667)
```

Is this something I can configure?

I've investigated a bit better and I've seen that if I have more than one broker they will be randomly generated.
Can I somehow do that also even if using just one broker?

**Comment by mguenther** [comment]
Currently, the single broker scenario does not allow to use a randomly generated port. It hardwires the `listeners` to `PLAINTEXT://localhost:9092`. I think I've missed this when we switched over to the `listeners` due to the deprecation/removal of `KafkaConfig$.MODULE$.PortProp()` and had to make sure that - in the multi-broker scenario - everything will continue to work as expected (and assigned ports will be retained after broker churn).

So, no, this not something that you can configure right now. Let me think about it.
